name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.12.3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build and test
        run: pnpm build && pnpm test
      - name: Package dist/
        run: pnpm package
      - name: Test action
        uses: ./
        with:
          template-file: '__tests__/**/*.ejs'
          glob: true
          vars: |
            {
              "name": "test",
              "version": "1.0.0"
            }
